var SWEEP=SWEEP||{};SWEEP.SVG="http://www.w3.org/2000/svg";SWEEP.Simulation=function(a){function b(){requestAnimationFrame(b);TWEEN.update()}var c=this;this.width=a;this.sweepActive=!1;this.svg=document.createElementNS(SWEEP.SVG,"svg");this.svg.setAttribute("viewBox","-1, -1, 102, 102");this.svg.setAttribute("width",this.width+"px");this.svg.setAttribute("height",this.width+"px");document.body.appendChild(this.svg);bg=document.createElementNS(SWEEP.SVG,"rect");bg.setAttribute("x",-1);bg.setAttribute("y",-1);bg.setAttribute("width",102);bg.setAttribute("height",
102);bg.setAttribute("class","bg");this.svg.appendChild(bg);this.sweepline=new SWEEP.Sweepline(this);this.points=[];this.intersections=[];this.addLine(29,42,70,10);this.addLine(70,70,40,22);this.addLine(85,60,20,80);this.addLine(10,32,60,90);this.addLine(25,95,65,4);this.addLine(12,14,22,26);this.addLine(79,7,93,55);this.addLine(67,53,97,44);this.start=document.createElement("div");this.start.innerHTML="Sweep";this.start.setAttribute("class","button");this.start.addEventListener("click",function(){c.sweep()},
!1);document.body.appendChild(this.start);b()};
SWEEP.Simulation.prototype={constructor:SWEEP.Simulation,addPoint:function(a,b,c,d){a=new SWEEP.Point(this.svg,a,b,c,d);d?this.events.contains(a)?a.remove():(this.events.insert(a),this.intersections.push(a)):this.points.push(a);return a},addLine:function(a,b,c,d){var e=new SWEEP.Line(this),a=this.addPoint(a,b,e,!1),c=this.addPoint(c,d,e,!1);e.setPoints(a,c)},sweep:function(){if(!this.sweepActive){this.sweepActive=!0;this.cleanup();var a=this.events.getMin();void 0!==a?this.sweepline.sweepToPoint(a):
this.sweepline.sweepToEnd()}},cleanup:function(){var a=function(a,c){return a.compare(c)};this.sweepline.position=0;this.sweepline.setPosition();this.sweepline.status=new js_cols.RedBlackSet(a);this.events=new js_cols.RedBlackSet(a);for(a=0;a<this.points.length;a++)this.events.insert(this.points[a]);for(a=0;a<this.intersections.length;a++)this.intersections[a].remove();this.intersections=[]},outputIntersections:function(){console.log("\nIntersections:");for(var a=0;a<this.intersections.length;a++)console.log("\t"+
this.intersections[a].toString())}};SWEEP.Sweepline=function(a){this.simulation=a;this.line=document.createElementNS(SWEEP.SVG,"line");this.line.setAttribute("x1",0);this.line.setAttribute("x2",100);this.line.setAttribute("class","sweepline");this.simulation.svg.appendChild(this.line);this.position=0;this.setPosition();this.status=void 0;this.pairs=[]};
SWEEP.Sweepline.prototype={constructor:SWEEP.Sweepline,setPosition:function(){this.line.setAttribute("y1",this.position);this.line.setAttribute("y2",this.position)},eventCall:function(){var a=this.current;if(a.intersection){console.log("Event:"+a.toString()+"; Switching; Status:");var b=this.status.clone();this.status.clear();this.status.insertAll(b);var b=this.status.predecessor(a.line[1]),c=this.status.successor(a.line[0]);null!==b&&this.pairs.push([b,a.line[1]]);null!==c&&this.pairs.push([a.line[0],
c])}else a.line.startPoint===a?(console.log("Event:"+a.toString()+"; Adding; Status:"),this.status.insert(a.line),b=this.status.predecessor(a.line),c=this.status.successor(a.line),null!==b&&this.pairs.push([b,a.line]),null!==c&&this.pairs.push([a.line,c])):(console.log("Event:"+a.toString()+"; Removing; Status:"),b=this.status.predecessor(a.line),c=this.status.successor(a.line),this.status.remove(a.line),null!==b&&null!==c&&this.pairs.push([b,c]));this.status.traverse(function(a){console.log("\t"+
a.toString())},this);this.doPairs()},doPairs:function(){0<this.pairs.length?this.intersectionCheck(this.pairs.pop()):this.sweepNext()},intersectionCheck:function(a){var b=a[0],c=a[1];this.action=0;b.line.style.stroke="red";c.line.style.stroke="red";a=b.intersect(c);null!==a&&this.simulation.addPoint(a[0],a[1],[b,c],!0);new SWEEP.Animation(this,{action:100},400,function(){var a=0.02*(50-Math.abs(this.action-50))+0.5;b.line.style.strokeWidth=a+"px";c.line.style.strokeWidth=a+"px"},function(){b.line.style.stroke=
"#ccc";c.line.style.stroke="#ccc";this.doPairs()})},sweepNext:function(){var a=this.simulation.events.successor(this.current);null!==a?this.sweepToPoint(a):this.sweepToEnd()},sweepToPoint:function(a){this.current=a;new SWEEP.Animation(this,{position:a.y},25*(a.y-this.position),function(){this.setPosition()},function(){a.animate(this)})},sweepToEnd:function(){new SWEEP.Animation(this,{position:100},25*(100-this.position),function(){this.setPosition()},function(){this.simulation.outputIntersections();
this.simulation.sweepActive=!1;this.status.isEmpty()||console.warn("status not empty")})}};SWEEP.Line=function(a){this.simulation=a;this.endPoint=this.startPoint=void 0;this.line=document.createElementNS(SWEEP.SVG,"line");this.line.setAttribute("class","line");this.simulation.svg.appendChild(this.line)};
SWEEP.Line.prototype={constructor:SWEEP.Line,setPoints:function(a,b){a.y<b.y?(this.startPoint=a,this.endPoint=b):(this.startPoint=b,this.endPoint=a);this.line.setAttribute("x1",this.startPoint.x);this.line.setAttribute("y1",this.startPoint.y);this.line.setAttribute("x2",this.endPoint.x);this.line.setAttribute("y2",this.endPoint.y)},compare:function(a){return this.getSweepIntersection()<a.getSweepIntersection()?-1:a.getSweepIntersection()<this.getSweepIntersection()?1:0},getSweepIntersection:function(){var a=
(this.endPoint.y-this.startPoint.y)/(this.endPoint.x-this.startPoint.x);return(this.simulation.sweepline.position+0.001-(this.endPoint.y-a*this.endPoint.x))/a},intersect:function(a){var b=this.startPoint.x,c=this.startPoint.y,d=this.endPoint.x,e=this.endPoint.y,g=a.startPoint.x,f=a.startPoint.y,h=a.endPoint.x,a=a.endPoint.y,i=(d-b)*(a-f)-(e-c)*(h-g);return 0!==i&&(f=((g-b)*(a-f)-(f-c)*(h-g))/i,g=(b-g+f*(d-b))/(h-g),0<=f&&1>=f&&0<=g&&1>=g)?[b+f*(d-b),c+f*(e-c)]:null},toString:function(){return"{line:["+
this.startPoint.toString()+","+this.endPoint.toString()+"]}"}};SWEEP.Point=function(a,b,c,d,e){this.svg=a;this.x=b;this.y=c;this.line=d;this.intersection=e;this.point=document.createElementNS(SWEEP.SVG,"circle");this.point.setAttribute("cx",b);this.point.setAttribute("cy",c);this.point.setAttribute("r",1);this.point.setAttribute("class","point");this.point.style.fill=this.intersection?"#157":"#999";this.svg.appendChild(this.point)};
SWEEP.Point.prototype={constructor:SWEEP.Point,animate:function(a){this.action=0;this.point.style.fill="red";new SWEEP.Animation(this,{action:100},400,function(){this.setSize(0.04*(50-Math.abs(this.action-50))+1)},function(){this.point.style.fill=this.intersection?"#157":"#999";a.eventCall()})},setSize:function(a){this.point.setAttribute("r",a)},toString:function(){return"{x:"+Math.round(100*this.x)/100+",y:"+Math.round(100*this.y)/100+"}"},remove:function(){this.svg.removeChild(this.point)},compare:function(a){return this.y<
a.y?-1:a.y<this.y?1:0}};SWEEP.Animation=function(a,b,c,d,e){a=(new TWEEN.Tween(a)).to(b,1*c);a.onUpdate(d);a.onComplete(e);a.start()};
